### ISSUE TITLE
Yoloact_ros for ROS1

### ISSUE THREAD

**Issue by germal** [IntelligentRoboticsLabs/yolact_ros_3d#7]
Hello @fmrico ,

I would try yoloact_ros on my robot  , would be possible for you to release a ROS1 version ?
Thanks a lot ,
germal

**Comment by fmrico** [comment]
Hi @germal 

yolact_ros is already working in ROS1 [here](https://github.com/Eruvae/yolact_ros) 

If you are asking if I can do an implementation of yolact_ros_3d for ROS1, it is not in my plans. 

As this is an Open Source project, I can guide, help you and review your work if you make a PR for this. Of course, if you finance this development, we can start working on it.

Best

**Comment by germal** [comment]
Hello @fmrico 

I would like to have a budget to finance your projects , they are really awesome and well supported, but I am only a student . 
Thank you for the link to yoloact_ros. 
Thanks a lot,
Regards
germal
